### ISSUE TITLE
About the low depth sequence assmble

### ISSUE THREAD

**Issue by ld9866** [lbcb-sci/GNNome#3]
Dear developer:
I am trying to assemble the genome using about 15-20X nanopore data and about 15X illumina genome. The genome we are going to assemble , I would like to ask if this is feasible. I don't know if the software can meet this need?
Best day!

**Comment by lvrcek** [comment]
Hi,

This tool does not support Illumina data, as it was implemented to work with long reads, mainly PacBio HiFi and Oxford Nanopore. For the 15-20X ONT data that you mention, you can try to first build the graph with Raven and do the decoding with GNNome. THe necessary steps are stated in README, but let me know if you will have any other questions.

**Comment by ld9866** [comment]
Thank you!
