### ISSUE TITLE
Erro in polish step IndexError: list index out of range

### ISSUE THREAD

**Issue by ld9866** [lbcb-sci/GNNome#4]
Dear developer:
we used the gnnome well in example data, but what we met the erro is we used the nanopore assemble from raven “raven --threads 100 sample.fastq.gz > sample.raven.contigs.fasta” and we got the fasta file ,then we used the fa2gfa translate the fa to gfa format “fa2gfa -i sample.raven.contigs.fasta -o sample.raven.contig.gfa”.

When we used the step "python /home/test/Software/GNNome-0.4.0/create_inference_graphs.py --reads sample.fastq.gz --gfa sample.raven.contig.gfa --asm raven --out sample.raven" we met the erro：

Starting to parse assembler output
Starting to loop over GFA
Elapsed time: 58s
Elapsed time: 58s
Calculating similarities...
0it [00:00, ?it/s]
Done!
Elapsed time: 58s
Traceback (most recent call last):
  File "/home/test/Software/GNNome-0.4.0/create_inference_graphs.py", line 50, in <module>
    create_inference_graph(gfa, reads, out, asm)
  File "/home/test/Software/GNNome-0.4.0/create_inference_graphs.py", line 13, in create_inference_graph
    graph, pred, succ, reads, edges, read_to_node, _ = graph_parser.only_from_gfa(gfa_path, training=False, reads_path=reads_path, get_similarities=True)
  File "/home/test/Software/GNNome-0.4.0/graph_parser.py", line 345, in only_from_gfa
    graph_dgl = dgl.from_networkx(graph_nx, node_attrs=node_attrs, edge_attrs=edge_attrs)
  File "/home/test/anaconda3/envs/gnnome/lib/python3.8/site-packages/dgl/convert.py", line 1345, in from_networkx
    g.edata[attr] = F.copy_to(_batcher(attr_dict[attr]), g.device)
  File "/home/test/anaconda3/envs/gnnome/lib/python3.8/site-packages/dgl/convert.py", line 1307, in _batcher
    if F.is_tensor(lst[0]):
IndexError: list index out of range

Can you help us and tell us how to solve the problem?

**Comment by lvrcek** [comment]
The issue might be in the fact that you run Raven to get the assembly, which you then convert into the GFA file. However, this is not the intended use of the tool, as it was implemented to work with assembly graphs prior to their simplification (before the assembly sequence/FASTA file is generated by Raven). The GFA file you created most likely represents a graph with no edges, and the error comes from there.

If you installed Raven according to the instructions in README, by running the `python install_tools.py` command, you should have a version that outputs a graph in the GFA format when you run it---no need to convert from FASTA to GFA yourself. The name of the file should be `graph_1.gfa` and this is the GFA file that you want to pass to the `create_inference_graphs.py` script. Therefore, the only change you need to make is:
```
python /home/test/Software/GNNome-0.4.0/create_inference_graphs.py --reads sample.fastq.gz --gfa <full_path_to_raven_output>/graph_1.gfa --asm raven --out sample.raven
```

Let me know if this works!

Best,
Lovro

**Comment by ld9866** [comment]
I read the README once again, we all know the hifiasm could generate the gfa file through "./vendor/hifiasm-0.18.8/hifiasm --prt-raw -o example/hifiasm/output/ecoli_asm -t32 -l0 example/ecoli.fasta.gz"
But the raven result is fasta ,could you just think the example data is nanopore to give me a example code to generate the "raven gfa" result.
Best day!

**Comment by lvrcek** [comment]
Which version of Raven are you using and how did you install it?

If you downloaded it from the master branch, then it will not output the GFA. The one that is downloaded from the script should be from the `print_graphs` branch, which then outputs the GFA after the overlap phase. So you can either try to manually install the version on the [print_graphs branch](https://github.com/lbcb-sci/raven/tree/print_graphs), or [run the install_tools.py](https://github.com/lbcb-sci/GNNome?tab=readme-ov-file#4-install-tools-used-for-constructing-assembly-graphs) in case you didn't do it before.

**Comment by ld9866** [comment]
Thank you! we think we know the erro reason!
